"""
Reflectance Reconstruction from Tristimulus Values (Object Colors)
================================================================
Computes a reconstructed spectral reflectance curve from an
illuminant-referenced triplet of tristimulus values
representing an object color (within the object color solid).

Version 2020_01_24 Scott Allen Burns
"""

import numpy as np
from scipy import linalg
import warnings
warnings.simplefilter("ignore")

def reflectance_reconstruction(d, cmfs_w, XYZ_w, max_iterations=20, tolerance=1e-8):
    """
    Computes a reconstructed spectral reflectance curve from
    an illuminant-referenced triplet of tristimulus values
    representing an object color (within the object color solid).

    Parameters
    ----------
    d: nxn array of finite differencing constants, obtained
           from function method_3_prep.py. (n is the number
           of wavelength bins (rows) used in the CMFs.)
    cmfs_w: nx3 array of illuminant-w-referenced CMFs,
           obtained from function method_3_prep.py.
    XYZ_w: a three element vector of illum-w-referenced
           tristimulus values in the 0 <= Y <= 1 convention range.
    max_iterations: upper limit on iterations (defaults to 20).
    tolerance: determines when the linear equations for a
           stationary point are satisfied (default is 1e-8).

    Returns
    -------
    nx1 vector of spectral reflectance values (or zeros if failure).

    Notes
    -----
    The input parameters d and cmfs_w can be generated by function
    method_3_prep.py. For a given illuminant, method_3_prep
    needs to be called only once. Multiple calls to method_3
    may then follow for various tristimulus values. This is a
    typical use case, and avoids repeated computation of d and
    cmfs_w.

    The XYZ_w supplied to method_3 must fall strictly within the
    object color solid (i.e., be a valid object color that can be
    represented by a reflectance curve strictly between 0 and 1),
    or the method will fail and return a vector of zeros.

    The reflectance curve generated will always have values in
    the range 0 to 1, corresponding to valid object colors. If
    it is desired to expand the applicability of the method to
    any real color within the spectral locus (including emissive
    colors), use method_2.py instead.

    method_3 is based on "method 3" of Reference [1]. It also
    corresponds to method "LHTSS" (Least Hyperbolic Tangent Slope
    Squared) of Reference [2].

    References
    ----------
    [1] Burns SA. Numerical methods for smoothest reflectance
        reconstruction. Color Research & Application, Vol 45,
        No 1, 2020, pp 8-21.
    [2] Generating Reflectance Curves from sRGB Triplets, 2015
        http://scottburns.us/reflectance-curves-from-srgb/#LHTSS

    Acknowledgements
    ----------------
    Thanks to Adam J. Burns and Mark (kram1032) for assistance
    with translating from MATLAB to Python.

    """

    n = cmfs_w.shape[0]  # number of rows
    z = np.zeros(n)
    lam = np.zeros(3)
    for _ in range(max_iterations):
        r = (np.tanh(z)+1)/2
        sech2 = 1/(np.cosh(z)**2)
        d1 = np.diag(sech2/2)
        d1a = d1.dot(cmfs_w)
        d2 = np.diag(sech2*np.tanh(z))
        f = np.block([d.dot(z)+d1a.dot(lam), cmfs_w.T.dot(r)-XYZ_w])
        j = np.block([[d-np.diag(d2.dot(cmfs_w).dot(lam)), d1a], [d1a.T, np.zeros((3, 3))]])
        try:
            delta = linalg.solve(j, -f, assume_a='sym')
        except (linalg.misc.LinAlgError, ValueError):
            # print('Ill-conditioned or singular linear system detected.')
            # print('Check to make sure XYZ_w is within the object color solid.')
            return np.zeros(n)
        z += delta[0:n]
        lam += delta[n:n+3]
        if np.all(np.abs(f) < tolerance):
            return (np.tanh(z)+1)/2
    # print('Maximum number of iterations reached.')
    # print('Check to make sure XYZ_w is within the object color solid.')
    return np.zeros(n)


def reflectance_reconstruction_prep(cmfs, w):
    """
    Computes two arrays in preparation for the function
    reflectance_reconstruction.py. For a given illuminant, method_3_prep
    needs to be called only once. Multiple calls to
    method_3 may then follow for various tristimulus values.

    Parameters
    ----------
    cmfs: nx3 array of color matching functions, where n
          is the number of wavelength bins (rows) of cmfs.
    w: an n-element vector of relative illuminant magnitudes,
          scaled arbitrarily.

    Returns
    -------
    d: nxn array of finite differencing constants.
    cmfs_w: nx3 array of illuminant-w-referenced CMFs.

    Notes
    -----
    This function is identical to method_2_prep.

    Acknowledgements
    ----------------
    Thanks to Adam J. Burns and Mark (kram1032) for assistance
    with translating from MATLAB to Python.

    """

    # determine number of wavelength bins
    n = cmfs.shape[0]

    # build tri-diagonal array of finite differencing constants
    d = np.eye(n, n, k=-1) * -2 + np.eye(n, n) * 4 + np.eye(n, n, k=1) * -2
    d[0, 0] = 2
    d[n - 1, n - 1] = 2

    # build illuminant-w-referenced CMFs
    w1 = np.squeeze(w)
    w_norm = w1 / (w1.dot(cmfs[:, 1]))
    cmfs_w = np.diag(w_norm).dot(cmfs)

    return d, cmfs_w